"""Ijai runtime profiles.

See docs/dev/module-notes.md for design rationale and verification status.
"""

from __future__ import annotations

from dataclasses import replace

from ..types import (
    Action,
    CleanHistoryCapability,
    ConsumablesCapability,
    CoreCapability,
    DndCapability,
    MapCapability,
    ModelProfile,
    PointZoneCapability,
    Prop,
    RoomCleanCapability,
    ScheduleCapability,
    SettingsCapability,
    VoiceCapability,
)


# --- Cores ------------------------------------------------------------------
# Core grouping is orthogonal to the rich-cap layout grouping above: several
# distinct rich layouts share one core (STD covers v13/v14/v17), while one rich
# layout can carry two cores (v10 vs v16 differ in fan/sweep -> v16 is split
# out). Promoted spec-accurate from generate_runtime_specs.py.

# v13/v14/v15/v17/v18/v19 — the S10-era engine (hardware-verified on v17).
IJAI_CORE_STD = CoreCapability(
    status=Prop(2, 1),
    fault=Prop(2, 2),
    mode=Prop(2, 4),
    battery=Prop(3, 1),
    fan_speed=Prop(7, 5),
    water_level=Prop(7, 6),
    sweep_type=Prop(2, 8),
    repeat=Prop(7, 1),
    alarm=Prop(4, 1),
    volume=Prop(4, 2),
    start=Action(2, 1),
    stop=Action(2, 2),
    charge=Action(3, 1),
    status_map={0: 'idle', 1: 'idle', 2: 'paused', 3: 'returning', 4: 'docked', 5: 'cleaning', 6: 'cleaning', 7: 'cleaning', 8: 'idle'},
    fan_speeds={'slient': 0, 'standard': 1, 'medium': 2, 'turbo': 3},
    water_levels={'low': 0, 'mid': 1, 'high': 2},
    modes={'sweep': 0, 'sweep_and_mop': 1, 'mop': 2},
    sweep_types={'global': 0, 'mop': 1, 'edge': 2, 'area': 3, 'point': 4, 'remote': 5, 'explore': 6, 'room': 7, 'floor': 8},
)

# v1/v2/v3 — early engine (different fan/water label text than STD).
IJAI_CORE_LEGACY = CoreCapability(
    status=Prop(2, 1),
    fault=Prop(2, 2),
    mode=Prop(2, 4),
    battery=Prop(3, 1),
    fan_speed=Prop(7, 5),
    water_level=Prop(7, 6),
    sweep_type=Prop(2, 8),
    repeat=Prop(7, 1),
    alarm=Prop(4, 1),
    volume=Prop(4, 2),
    start=Action(2, 1),
    stop=Action(2, 2),
    charge=Action(3, 1),
    status_map={0: 'idle', 1: 'idle', 2: 'paused', 3: 'returning', 4: 'docked', 5: 'cleaning', 6: 'cleaning', 7: 'cleaning', 8: 'idle'},
    fan_speeds={'off': 0, 'energy_saving': 1, 'standard': 2, 'powerful': 3},
    water_levels={'low': 0, 'medium': 1, 'high': 2},
    modes={'sweep': 0, 'sweep_and_mop': 1, 'mop': 2},
    sweep_types={'global': 0, 'mop': 1, 'edge': 2, 'area': 3, 'point': 4, 'remote': 5, 'explore': 6, 'room': 7, 'floor': 8},
)

# v10 — legacy labels but a trimmed sweep-type set.
IJAI_CORE_V10 = CoreCapability(
    status=Prop(2, 1),
    fault=Prop(2, 2),
    mode=Prop(2, 4),
    battery=Prop(3, 1),
    fan_speed=Prop(7, 5),
    water_level=Prop(7, 6),
    sweep_type=Prop(2, 8),
    repeat=Prop(7, 1),
    alarm=Prop(4, 1),
    volume=Prop(4, 2),
    start=Action(2, 1),
    stop=Action(2, 2),
    charge=Action(3, 1),
    status_map={0: 'idle', 1: 'idle', 2: 'paused', 3: 'returning', 4: 'docked', 5: 'cleaning', 6: 'cleaning', 7: 'cleaning', 8: 'idle'},
    fan_speeds={'off': 0, 'energy_saving': 1, 'standard': 2, 'powerful': 3},
    water_levels={'low': 0, 'medium': 1, 'high': 2},
    modes={'sweep': 0, 'sweep_and_mop': 1, 'mop': 2},
    sweep_types={'global': 0, 'edge': 2, 'point': 4, 'remote': 5},
)

# v16 — shares v10's RICH layout but STD-style fan/water labels (hence split).
IJAI_CORE_V16 = CoreCapability(
    status=Prop(2, 1),
    fault=Prop(2, 2),
    mode=Prop(2, 4),
    battery=Prop(3, 1),
    fan_speed=Prop(7, 5),
    water_level=Prop(7, 6),
    sweep_type=Prop(2, 8),
    repeat=Prop(7, 1),
    alarm=Prop(4, 1),
    volume=Prop(4, 2),
    start=Action(2, 1),
    stop=Action(2, 2),
    charge=Action(3, 1),
    status_map={0: 'idle', 1: 'idle', 2: 'paused', 3: 'returning', 4: 'docked', 5: 'cleaning', 6: 'cleaning', 7: 'cleaning', 8: 'idle'},
    fan_speeds={'slient': 0, 'standard': 1, 'medium': 2, 'turbo': 3},
    water_levels={'low': 0, 'mid': 1, 'high': 2},
    modes={'sweep': 0, 'sweep_and_mop': 1, 'mop': 2},
    sweep_types={'global': 0, 'edge': 2, 'point': 4, 'remote': 5},
)


# ijai.vacuum.v1
IJAI_V1 = ModelProfile(
    profile_id='ijai.v1',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v1:2",),
    core=IJAI_CORE_LEGACY,
    max_properties=5,  # IJAI_CORE_LEGACY firmware rejects large property batches
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            beauty_point=Prop(9, 6),
            set_beauty_wall=Action(9, 5, in_piid=6, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        direction=Prop(7, 16),
        dirt_recognize=Prop(7, 35),
        pet_recognize=Prop(7, 36),
        ai_recognize=Prop(7, 42),
        carpet_booster=Prop(7, 44),
        carpet_avoid=Prop(7, 47),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
)

# ijai.vacuum.v2
IJAI_V2 = ModelProfile(
    profile_id='ijai.v2',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v2:2",),
    core=IJAI_CORE_LEGACY,
    max_properties=5,  # IJAI_CORE_LEGACY firmware rejects large property batches
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        shake_shift=Prop(7, 50),
        tank_shake=Prop(7, 48),
        direction=Prop(7, 16),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
)

# ijai.vacuum.v3
IJAI_V3 = ModelProfile(
    profile_id='ijai.v3',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v3:2",),
    core=IJAI_CORE_LEGACY,
    max_properties=5,  # IJAI_CORE_LEGACY firmware rejects large property batches
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        shake_shift=Prop(7, 50),
        tank_shake=Prop(7, 48),
        direction=Prop(7, 16),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
    voice=VoiceCapability(
        service=14,
        download_voice=Action(14, 1, in_piids=(1, 5, 6)),
        get_download_status=Action(14, 2, out_piids=(1, 2, 3, 4)),
        target_voice=Prop(14, 1),
        cur_voice=Prop(14, 2),
        download_status=Prop(14, 3),
        download_progress=Prop(14, 4),
        voice_url=Prop(14, 5),
    ),
)

# ijai.vacuum.v10, ijai.vacuum.v16
IJAI_V10 = ModelProfile(
    profile_id='ijai.v10',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v10:1",),
    core=IJAI_CORE_V10,
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            beauty_point=Prop(9, 6),
            set_beauty_wall=Action(9, 5, in_piid=6, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
    ),
    room_clean=RoomCleanCapability(
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 7, 8, 9, 17, 19)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        direction=Prop(7, 16),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
    voice=VoiceCapability(
        service=14,
        download_voice=Action(14, 1, in_piids=(1, 5, 6)),
        get_download_status=Action(14, 2, out_piids=(1, 2, 3, 4)),
        target_voice=Prop(14, 1),
        cur_voice=Prop(14, 2),
        download_status=Prop(14, 3),
        download_progress=Prop(14, 4),
        voice_url=Prop(14, 5),
    ),
)

# ijai.vacuum.v13
IJAI_V13 = ModelProfile(
    profile_id='ijai.v13',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v13:2",),
    core=IJAI_CORE_STD,
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            beauty_point=Prop(9, 6),
            set_beauty_wall=Action(9, 5, in_piid=6, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        tank_shake=Prop(7, 48),
        direction=Prop(7, 16),
        dirt_recognize=Prop(7, 35),
        pet_recognize=Prop(7, 36),
        ai_recognize=Prop(7, 42),
        carpet_booster=Prop(7, 44),
        carpet_avoid=Prop(7, 47),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
)

# ijai.vacuum.v14, ijai.vacuum.v15
IJAI_V14 = ModelProfile(
    profile_id='ijai.v14',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v14:2",),
    core=IJAI_CORE_STD,
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            beauty_point=Prop(9, 6),
            set_beauty_wall=Action(9, 5, in_piid=6, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        shake_shift=Prop(7, 50),
        tank_shake=Prop(7, 48),
        direction=Prop(7, 16),
        dirt_recognize=Prop(7, 35),
        pet_recognize=Prop(7, 36),
        ai_recognize=Prop(7, 42),
        carpet_booster=Prop(7, 44),
        carpet_avoid=Prop(7, 47),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
)

# ijai.vacuum.v17, ijai.vacuum.v18, ijai.vacuum.v19
IJAI_V17 = ModelProfile(
    profile_id='ijai.v17',
    brand='ijai',
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v17:2",),
    core=IJAI_CORE_STD,
    map=MapCapability(
        service=10,
        map_num=Prop(10, 3),
        current_map_id=Prop(10, 2),
        get_map_list=Action(10, 1, out_piids=(4,)),
        upload_by_mapid=Action(10, 2, in_piid=6, out_piids=(6, 7, 18)),
        upload_by_mapid_ii=Action(10, 14, in_piid=6, out_piids=(6, 7, 18, 21)),
        set_current_map=Action(10, 3, in_piid=6),
        point_zone=PointZoneCapability(
            service=9,
            zone_points=Prop(9, 2),
            target_point=Prop(9, 5),
            set_zone_point=Action(9, 8, in_piid=2, out_piids=(7, 8, 9)),
            start_zone_clean=Action(9, 3),
            start_point_clean=Action(9, 9, in_piid=5, out_piids=(7, 8, 9)),
            legacy_start_point_clean=Action(9, 1),
            pause_point_clean=Action(9, 2, in_piid=4),
            pause_zone_clean=Action(9, 4, in_piid=4),
            restrict_points=Prop(9, 3),
            set_virtual_wall=Action(9, 6, in_piid=3, out_piids=(7, 8, 9)),
            beauty_point=Prop(9, 6),
            set_beauty_wall=Action(9, 5, in_piid=6, out_piids=(7, 8, 9)),
            map_type=Prop(9, 8),
        ),
        map_list=Prop(10, 4),
        remember_state=Prop(10, 1),
        has_new_map=Prop(10, 19),
        del_map=Action(10, 4, in_piid=6),
        rename_map=Action(10, 5, in_piids=(6, 8)),
        build_new_map=Action(10, 11, in_piid=14),
        reset_map=Action(10, 10),
        current_path=Prop(10, 5),
        start_cleaning_point=Prop(10, 15),
        end_cleaning_point=Prop(10, 16),
        get_current_path=Action(10, 12, in_piids=(15, 16), out_piids=(5,)),
        room_id_name_list=Prop(10, 17),
        split_points=Prop(10, 12),
        arrange_room_ids=Prop(10, 11),
        get_map_room_list=Action(10, 13, in_piid=2, out_piids=(17,)),
        rename_room=Action(10, 7, in_piids=(6, 9, 10), out_piids=(6, 7, 18)),
        arrange_room=Action(10, 8, in_piids=(6, 11, 13), out_piids=(6, 7, 18)),
        split_room=Action(10, 9, in_piids=(6, 9, 12, 13), out_piids=(6, 7, 18)),
        mijia_room_list=Prop(10, 22),
        set_mijia_room_list=Action(10, 18, in_piids=(6, 22)),
    ),
    room_clean=RoomCleanCapability(
        room_ids=Prop(2, 10),
        start=Action(2, 7, in_piid=10),
        clean_room_ids=Prop(7, 24),
        clean_room_mode=Prop(7, 25),
        clean_room_oper=Prop(7, 26),
        set_room_clean=Action(7, 3, in_piids=(24, 25, 26)),
    ),
    schedule=ScheduleCapability(
        service=8,
        add=Action(8, 1, in_piids=(1, 2, 3, 4, 5, 6, 11, 14, 12, 16)),
        delete=Action(8, 2, in_piid=1),
        get=Action(8, 3, out_piids=(15,)),
        add_iii=Action(8, 6, in_piids=(1, 2, 3, 4, 5, 6, 11, 12, 14, 16, 17, 19), out_piids=(20,)),
        order_id=Prop(8, 1),
        enable=Prop(8, 2),
        day=Prop(8, 3),
        hour=Prop(8, 4),
        minute=Prop(8, 5),
        repeat=Prop(8, 6),
        clean_way=Prop(8, 7),
        suction=Prop(8, 8),
        water=Prop(8, 9),
        twice_clean=Prop(8, 10),
        mapid=Prop(8, 11),
        room_count=Prop(8, 12),
        room_data=Prop(8, 13),
        orderdata=Prop(8, 15),
    ),
    settings=SettingsCapability(
        mop_route=Prop(7, 7),
        shake_shift=Prop(7, 50),
        tank_shake=Prop(7, 48),
        direction=Prop(7, 16),
        dirt_recognize=Prop(7, 35),
        pet_recognize=Prop(7, 36),
        ai_recognize=Prop(7, 42),
        carpet_booster=Prop(7, 44),
        carpet_avoid=Prop(7, 47),
        map_encrypt=Prop(7, 55),
        multi_prop_vacuum=Prop(7, 45),
    ),
    consumables=ConsumablesCapability(
        side_brush_hours=Prop(7, 9),
        main_brush_hours=Prop(7, 11),
        hypa_hours=Prop(7, 13),
        mop_hours=Prop(7, 15),
        door_state=Prop(7, 3),
        cloth_state=Prop(7, 4),
        reset_consumable=Action(7, 1, in_piid=17),
    ),
    clean_history=CleanHistoryCapability(
        start_time=Prop(7, 27),
        use_time=Prop(7, 28),
        clean_area=Prop(7, 29),
        map_url=Prop(7, 30),
        clean_mode=Prop(7, 31),
        clean_way=Prop(7, 32),
        current_map=Prop(7, 33),
        task_status=Prop(7, 37),
    ),
    dnd=DndCapability(
        service=12,
        set_notdisturb=Action(12, 1, in_piids=(1, 2, 3, 4, 5, 6)),
        enable=Prop(12, 1),
        start_hour=Prop(12, 2),
        start_minute=Prop(12, 3),
        end_hour=Prop(12, 4),
        end_minute=Prop(12, 5),
        timezone=Prop(12, 6),
    ),
    voice=VoiceCapability(
        service=14,
        download_voice=Action(14, 1, in_piids=(1, 5, 6)),
        get_download_status=Action(14, 2, out_piids=(1, 2, 3, 4)),
        target_voice=Prop(14, 1),
        cur_voice=Prop(14, 2),
        download_status=Prop(14, 3),
        download_progress=Prop(14, 4),
        voice_url=Prop(14, 5),
    ),
)

# ijai.vacuum.v16 — identical RICH layout to v10, but a distinct core (STD-style
# fan/water labels). Split out so v16 doesn't inherit v10's wrong labels.
IJAI_V16 = replace(
    IJAI_V10,
    profile_id='ijai.v16',
    core=IJAI_CORE_V16,
    notes=("urn:miot-spec-v2:device:vacuum:0000A006:ijai-v16:1",),
)
